# **Pandas Assignment**

## Assignment  - Pandas and EDA

Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on All Time Olympic Games Medals, and does some basic data cleaning.

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


## Loading the dataset for Part - 1

In [2]:
import pandas as pd
df = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/Data science/olympics.csv', index_col = 0, skiprows=1)
df.head()

№ Summer  01 !  02 !  ...  02 !.2  03 !.2  Combined total
Afghanistan (AFG)              13     0     0  ...       0       2               2
Algeria (ALG)                  12     5     2  ...       2       8              15
Argentina (ARG)                23    18    24  ...      24      28              70
Armenia (ARM)                   5     1     2  ...       2       9              12
Australasia (ANZ) [ANZ]         2     3     4  ...       4       5              12

[5 rows x 15 columns]

In [3]:
# Shape of the dataset
df.shape

(147, 15)

**Observation:** 
* This dataset contains 147 rows and 15 columns.

In [4]:
# Lets rename the columns names.
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  ...  Bronze.2  Combined total   ID
Afghanistan        13     0       0  ...         2               2  AFG
Algeria            12     5       2  ...         8              15  ALG
Argentina          23    18      24  ...        28              70  ARG
Armenia             5     1       2  ...         9              12  ARM
Australasia         2     3       4  ...         5              12  ANZ

[5 rows x 16 columns]

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [5]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
**1. which country has won the most gold medals in summer games**<br>
 *This function should return a single string value.*

In [7]:
def answer_one():
  return df['Gold'].idxmax()
answer_one()

'United States'

### Question 2
**Which country had the biggest difference between their summer and winter gold medal counts?**

*This function should return a single string value.*

In [8]:
def answer_two():
  return (df['Gold'] - df['Gold.1']).idxmax()
answer_two()

'United States'

**3. Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count?**
                                                     ** (Summer Gold−Winter Gold)/Total Gold**
                                                     **Only include countries that have won at least 1 gold in both summer and winter.**

### Question 3
**Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? **

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [9]:
def answer_three():
  return ((df['Gold'] > 0)- (df['Gold.1'] > 0)/df['Gold.2']).idxmax()
answer_three()

'Algeria'

## Question 4
**Write a function that creates a Series called "Points" which is a weighted value where each gold medal (Gold.2) counts for 3 points, silver medals (Silver.2) for 2 points, and bronze medals (Bronze.2) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.**
*This function should return a Series named `Points` of length 146*

In [0]:
def answer_four():
  df['Points'] = df['Gold.2']*3 + df['Silver.2']*2 + df['Bronze.2']*1
  return df['Points']
answer_four()

Afghanistan                            2
Algeria                               27
Argentina                            130
Armenia                               16
Australasia                           22
Australia                            919
Austria                              488
Azerbaijan                            43
Bahamas                               24
Bahrain                                1
Barbados                               1
Belarus                              149
Belgium                              273
Bermuda                                1
Bohemia                                5
Botswana                               2
Brazil                               184
British West Indies                    2
Bulgaria                             408
Burundi                                3
Cameroon                              12
Canada                               794
Chile                                 24
China                               1101
Colombia        

In [10]:
def answer_four():
    d = {}
    for i in range(len(df)):
        d[df.iloc[i].name] = df.iloc[i]['Gold.2']*3 + df.iloc[i]['Silver.2']*2 + df.iloc[i]['Bronze.2']
    return pd.Series(d)
answer_four()

Afghanistan                           2
Algeria                              27
Argentina                           130
Armenia                              16
Australasia                          22
                                   ... 
Yugoslavia                          171
Independent Olympic Participants      4
Zambia                                3
Zimbabwe                             18
Mixed team                           38
Length: 146, dtype: int64

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

In [12]:
import pandas as pd
import numpy as np
census_df = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/Data science/census.csv')
census_df.head()

SUMLEV  REGION  DIVISION  ...  RNETMIG2013  RNETMIG2014 RNETMIG2015
0      40       3         6  ...     1.383282     1.724718    0.712594
1      50       3         6  ...    -2.722002     2.592270   -2.187333
2      50       3         6  ...    22.727626    20.317142   18.293499
3      50       3         6  ...    -7.167664    -3.978583  -10.543299
4      50       3         6  ...    -5.403729     0.754533    1.107861

[5 rows x 100 columns]

### Question 5
**Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)**

*This function should return a single string value.*

In [13]:
def answer_five():
  #The .size() built-in method of DataFrameGroupBy objects actually returns a Series object with the group sizes and not a DataFrame.
  #If you want a DataFrame whose column is the group sizes, indexed by the groups, with a custom name, you can use the .to_frame() method and use the desired column name as its argument.
  df=census_df[census_df['SUMLEV'] == 50]
  df = census_df.groupby( [ "SUMLEV", "STNAME"] ).size().to_frame(name = 'count').reset_index() 
  return df.loc[df['count'].idxmax()]['STNAME']
answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [16]:
def answer_six():
    import numpy as np
    df = census_df[census_df['SUMLEV']==50]
    df1 = df.sort_values(by='CENSUS2010POP', ascending = False).groupby('STNAME').head(3).copy()
    df1 = df1.groupby('STNAME').agg({'CENSUS2010POP':np.sum})
    df1 = df1.sort_values(by ='CENSUS2010POP', ascending = False)
    return list(df1.head(3).index.values)
answer_six()

['California', 'Texas', 'Illinois']

In [19]:
# ALternative method
def answer_six():
    df=census_df[census_df['SUMLEV'] == 50]
    df1=df.sort_values(by=['STNAME','POPESTIMATE2015'],ascending=False).groupby('STNAME').head(3).copy()
    df2 = df1.reset_index().groupby("STNAME").sum().sort_values(by=['POPESTIMATE2015'],ascending=False).head(3).copy()
    return list(df2.index.values)
answer_six()

['California', 'Texas', 'Illinois']

### Question 7
**Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)**

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [21]:
def answer_seven():
  df=census_df[census_df['SUMLEV'] == 50]
  df['BKP'] = df[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012',
                      'POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].std(axis=1)
  return df.loc[df['BKP'].idxmax()]['CTYNAME']
answer_seven()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


'Harris County'

In [23]:
# Alternative method
def answer_seven():
    df = census_df[census_df['SUMLEV']==50]
    df['max'] = df[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].max(axis =1)
    df['min'] = df[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']].min(axis =1)
    df['difference'] = abs(df['max'] - df['min'])
    return df.loc[df['difference'].idxmax()]['CTYNAME']
answer_seven()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

**Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.**

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [24]:
def answer_eight():
  df=census_df[census_df['SUMLEV']==50]
  region_1 = df['REGION']==1
  region_2 = df['REGION']==2
  county_name = df['CTYNAME'].str.startswith('Washington')
  pop_estimate = df['POPESTIMATE2015'] > df['POPESTIMATE2014']
  df = df[(region_1|region_2)&county_name&pop_estimate]
  return df[['STNAME','CTYNAME']]
answer_eight()



STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County